ALTER TABLE "Mystery"
ADD COLUMN "suspectsMeta" JSONB NOT NULL DEFAULT '[]'::JSONB,
ADD COLUMN "locationsMeta" JSONB NOT NULL DEFAULT '[]'::JSONB,
ADD COLUMN "weaponsMeta" JSONB NOT NULL DEFAULT '[]'::JSONB;
